### PR TITLE
Header & Footer

### PR DESCRIPTION
**Pull request by ad9311**
# Project 3: Using Bootstrap - Milestone 1

Created the header and footer of the page and applied the Bootstrap classes.
Follow the mobile-first principle.

This repository was created by @ad9311 and @JuliCarracedo

### CODE REVIEW

**Review by mricanho — COMMENTED** [review]
# 🔴 Invalid Submission 🔴  

Hello @ad9311 @JuliCarracedo, unfortunately, I need to invalid this submission, remember that all your linters have to pass in order to continue the Pull Request process.

- Right now you have 2 errors in your CSS and those trigger the alert.
- Add a section in your README file like "Getting Started", here you may give instructions on setting up your project locally.

You should make sure that your repo looks professional before review. Please take a step back and read a lesson [here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/). Then apply 3 simple rules from this lesson (it will be easy as you can use a template provided there). This Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready!

You can contact me on slack if you have any questions just search for me as @ Miguel Ricaño.

### 💻 👩🏽‍💻  Happy Coding!👨🏽‍💻  🖥️

**Review by sinansevgi — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 
-----

Hello team,
Good Job. There are three small issues you should fix before you continue with your journey :wave: 

**_Kindly check the issues below._**

-----
- [ ] The search field brokes the design just before passing tablet view. Please check the screenshots.

| ................ | ............... |
| ------------- | ------------- |
| image1  |image2  |

----------

- [ ] Hamburger menu button overflowing/not visible on tablet view.
image

-----------

- [ ] Alignment of copyright info isn't correct on tablet and desktop view.

| Original | Yours |
| ------------- | ------------- |
| image1 | image2  |

-----

## "As described in the [Code reviews limit Policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 code reviews left for this project."

-----
You can reply to this conversation if you have any questions or need elaboration. :wave: 
Sinan Sevgi

**Comment by ad9311** [comment]
Fix the mentioned issues and made the necessary changes.

**Review by george-shammar — APPROVED** [review]
### **STATUS: APPROVED** :heavy_check_mark:

**Congratulations and thank you for adopting the mandatory requirements by the previous reviewer.** 

**You can go ahead and merge this branch.**

[OPTIONAL]
**Below are some changes that will really make this project look exactly like the original. Please take time and implement it.**

- [ ] **Adjust your margins or padding in the footer. Please see below:**
Original
image

Yours
image

- [ ] **Main navigation menu and search bar to fill up the container.**
Original
image

Yours
image

- [ ] **The horizontal scroll bar is showing in your desktop version, it means an element has a width bigger than the viewport. Please fix it.**

**Pull request merged**
